# Generated by Django 3.0.2 on 2020-03-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0007_stock_stock_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedbak_msg',
            new_name='feedback_msg',
        ),
    ]
