# Generated by Django 3.0.2 on 2020-03-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0008_auto_20200322_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_que',
            field=models.CharField(max_length=3000),
        ),
    ]
