# Generated by Django 3.0.2 on 2020-03-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0010_auto_20200322_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_msg',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
