# Generated by Django 3.0.2 on 2020-03-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0013_auto_20200322_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_msg',
            field=models.CharField(default='Not Answered by Admin yet', max_length=3000),
        ),
    ]
